import type { PageContent } from "@/db/schema";

export const showcaseContent: PageContent = {
  blocks: [
    {
      id: "showcase-app-header",
      type: "app-header",
      variant: "default",
      anchorId: "top",
      props: {
        title: "Nanofactory",
        logoAssetId: undefined,
        logoLightAssetId: undefined,
        logoDarkAssetId: undefined,
        collapseBreakpoint: "md",
        alwaysMobile: false,
        showModeSwitcher: true,
        menuItems: [
          { label: "Hero", anchorId: "hero" },
          { label: "Features", anchorId: "features" },
          { label: "Timeline", anchorId: "timeline" },
          { label: "Gallery", anchorId: "gallery" },
          { label: "Pricing", anchorId: "pricing" },
          { label: "Testimonials", anchorId: "testimonials" },
          { label: "FAQ", anchorId: "faq" },
          { label: "CTA", anchorId: "cta" },
        ],
        socialLinks: [
          { label: "GitHub", url: "https://github.com", icon: "link" },
        ],
      },
    },
    {
      id: "showcase-hero-default",
      type: "hero",
      variant: "default",
      anchorId: "hero",
      props: {
        eyebrow: "Feature blocks showcase",
        title: "Build pages with reusable blocks",
        subtitle:
          "The feature blocks tab now shows the full library in one place, so each block can be inspected in context.",
        buttonText: "Explore features",
        buttonAnchor: "features",
        imageAssetId: "showcase-hero-media",
      },
    },
    {
      id: "showcase-hero-centered",
      type: "hero",
      variant: "centered",
      anchorId: "hero-centered",
      props: {
        eyebrow: "Centered hero",
        title: "Lead with a shorter message",
        subtitle:
          "This variant keeps the copy compact and puts the CTA front and center for focused landing pages.",
        buttonText: "See the next section",
        buttonAnchor: "timeline",
        imageAssetId: "showcase-hero-centered-media",
      },
    },
    {
      id: "showcase-features-default",
      type: "features",
      variant: "default",
      anchorId: "features",
      props: {
        sectionTitle: "Features · Default list",
        animate: true,
        items: [
          {
            title: "Clear stacked list for quick scannability",
            content: "Simple enough for supporting content after hero.",
            imageAssetId: "showcase-feature-01",
          },
          {
            title: "Simple enough for supporting content after hero",
            content: "Keeps the copy and structure easy to maintain.",
            imageAssetId: "showcase-feature-02",
          },
          {
            title: "Keeps the copy and structure easy to maintain",
            content: "Works well as a stable, reusable default layout.",
            imageAssetId: "showcase-feature-03",
          },
        ],
        borderRadius: "lg",
      },
    },
    {
      id: "showcase-features-cards",
      type: "features",
      variant: "cards",
      anchorId: "features-cards",
      props: {
        sectionTitle: "Features · Cards",
        animate: true,
        items: [
          {
            title: "Card grouping makes each point feel more distinct",
            content: "Good fit for short high-signal feature blurbs.",
            imageAssetId: "showcase-feature-01",
          },
          {
            title: "Useful when you want a denser but still readable layout",
            content: "The card structure adds visual rhythm.",
            imageAssetId: "showcase-feature-02",
          },
          {
            title: "Good fit for short high-signal feature blurbs",
            content: "Useful when you want each item to feel like a tile.",
            imageAssetId: "showcase-feature-03",
          },
        ],
        borderRadius: "lg",
      },
    },
    {
      id: "showcase-timeline",
      type: "timeline",
      variant: "default",
      anchorId: "timeline",
      props: {
        sectionTitle: "Timeline · Roadmap",
        animate: true,
        items: [
          {
            meta: "01",
            date: "Q1 2026",
            status: "Planned",
            title: "Shape the product",
            content: "Define the content model, refine the editor flow, and keep the first version focused.",
          },
          {
            meta: "02",
            date: "Q2 2026",
            status: "In progress",
            title: "Build the core",
            content: "Ship the key page blocks, the editor interactions, and the content publishing flow.",
          },
          {
            meta: "03",
            date: "Q3 2026",
            status: "Ready",
            title: "Launch and iterate",
            content: "Open up the showcase and keep refining the details based on real usage.",
          },
        ],
      },
    },
    {
      id: "showcase-gallery",
      type: "gallery",
      variant: "default",
      anchorId: "gallery",
      props: {
        sectionTitle: "Gallery · Image grid",
        animate: true,
        columns: 3,
        imageHeightMode: "fixed",
        items: [
          {
            assetId: "showcase-gallery-01",
            entryAnchor: "gallery-item-1",
            title: "Gallery item one",
            description: "A compact card with title, description, price, and meta fields.",
            price: "$120",
            meta: "Limited edition",
          },
          {
            assetId: "showcase-gallery-02",
            entryAnchor: "gallery-item-2",
            title: "Gallery item two",
            description: "Useful for collections, product shots, or visual story fragments.",
            price: "$95",
            meta: "In stock",
          },
          {
            assetId: "showcase-gallery-03",
            entryAnchor: "gallery-item-3",
            title: "Gallery item three",
            description: "The preview still renders even before assets are attached.",
            price: "$75",
            meta: "Ships soon",
          },
        ],
      },
    },
    {
      id: "showcase-projects-gallery",
      type: "projects-gallery",
      variant: "default",
      anchorId: "projects",
      props: {
        sectionTitle: "Projects · Nested galleries",
        animate: true,
        galleryAnchor: "projects",
        items: [
          {
            projectAnchor: "project-alpha",
            galleryAnchor: "alpha-gallery",
            title: "Project Alpha",
            description: "A nested gallery block that can point to project detail pages.",
            descriptionMd: "A nested gallery block that can point to project detail pages.",
            price: "",
            meta: "2 entries",
            imageAssetId: "showcase-project-01",
            galleryItems: [
              {
                kind: "image",
                assetId: "showcase-project-entry-01",
                entryAnchor: "project-alpha-alpha-gallery-item-1",
                title: "Alpha entry one",
                description: "",
                contentMd: "",
                price: "",
                meta: "",
              },
              {
                kind: "markdown",
                assetId: "showcase-project-entry-02",
                entryAnchor: "project-alpha-alpha-gallery-item-2",
                title: "Alpha entry two",
                description: "",
                contentMd: "Markdown entry used to show mixed gallery content.",
                price: "",
                meta: "",
              },
            ],
          },
          {
            projectAnchor: "project-beta",
            galleryAnchor: "beta-gallery",
            title: "Project Beta",
            description: "A second card to show the grid rhythm across more than one item.",
            descriptionMd: "A second card to show the grid rhythm across more than one item.",
            price: "",
            meta: "2 entries",
            imageAssetId: "showcase-project-02",
            galleryItems: [
              {
                kind: "image",
                assetId: "showcase-project-entry-03",
                entryAnchor: "project-beta-beta-gallery-item-1",
                title: "Beta entry one",
                description: "",
                contentMd: "",
                price: "",
                meta: "",
              },
              {
                kind: "image",
                assetId: "showcase-gallery-02",
                entryAnchor: "project-beta-beta-gallery-item-2",
                title: "Beta entry two",
                description: "",
                contentMd: "",
                price: "",
                meta: "",
              },
            ],
          },
        ],
      },
    },
    {
      id: "showcase-pricing",
      type: "pricing",
      variant: "default",
      anchorId: "pricing",
      props: {
        sectionTitle: "Pricing · Plans",
        subtitle:
          "Three tiers that show how the pricing block handles featured plans, supporting copy, and action buttons.",
        featuredIndex: 1,
        plans: [
          {
            title: "Starter",
            price: "$19",
            description: "For quick launches with minimal setup.",
            buttonText: "Choose Starter",
            buttonHref: "#",
            includes: ["1 seat", "Basic support", "Core features"],
          },
          {
            title: "Growth",
            price: "$49",
            description: "For teams that need more room to move.",
            buttonText: "Choose Growth",
            buttonHref: "#",
            includes: ["5 seats", "Priority support", "Advanced features"],
          },
          {
            title: "Scale",
            price: "$99",
            description: "For projects that need the most flexibility.",
            buttonText: "Contact sales",
            buttonHref: "#",
            includes: ["Unlimited seats", "Dedicated support", "Custom setup"],
          },
        ],
      },
    },
    {
      id: "showcase-testimonials",
      type: "testimonials",
      variant: "default",
      anchorId: "testimonials",
      props: {
        sectionTitle: "Testimonials · Social proof",
        subtitle: "Short quotes and author details for a lightweight testimonial block.",
        animate: true,
        items: [
          {
            quote: "The editor stays simple, so the team can move fast without losing structure.",
            name: "Ava Chen",
            role: "Product designer",
            imageAssetId: "showcase-testimonial-01",
          },
          {
            quote: "We shipped our first version quickly and still have room to grow the page later.",
            name: "Daniel Brooks",
            role: "Founder",
            imageAssetId: "showcase-testimonial-02",
          },
          {
            quote: "Clear sections, clear controls, and no unnecessary complexity in the workflow.",
            name: "Mina Patel",
            role: "Operations lead",
            imageAssetId: "showcase-testimonial-03",
          },
          {
            quote: "The content model stays understandable even as the page grows.",
            name: "Jordan Lee",
            role: "Content lead",
            imageAssetId: "showcase-testimonial-04",
          },
        ],
      },
    },
    {
      id: "showcase-faq",
      type: "faq",
      variant: "default",
      anchorId: "faq",
      props: {
        sectionTitle: "FAQ · Common questions",
        subtitle: "A compact accordion block for answering the questions people ask before they buy.",
        animate: true,
        items: [
          {
            question: "What is the FAQ block for?",
            answer:
              "It is for compact, scannable answers to common questions that would otherwise clutter the page.",
          },
          {
            question: "Can I reorder the questions?",
            answer:
              "Yes. Questions are stored in the block content and can be reordered from the editor just like other list-based blocks.",
          },
          {
            question: "Does it work on mobile?",
            answer:
              "Yes. The default layout keeps each question in a tap-friendly disclosure row and expands cleanly on small screens.",
          },
        ],
      },
    },
    {
      id: "showcase-cta-default",
      type: "cta",
      variant: "default",
      anchorId: "cta",
      props: {
        title: "Call to action · Default",
        buttonText: "Start building",
        buttonHref: "#top",
        animate: true,
      },
    },
    {
      id: "showcase-footer-social-icons",
      type: "footer",
      variant: "default",
      anchorId: "footer",
      props: {
        leftTitle: "Footer · Social links",
        logoAssetId: undefined,
        siteName: "Nanofactory",
        siteDescription: "A small, readable footer to close the feature blocks showcase.",
        socialLinksTitle: "Available icons",
        socialLinks: [
          { label: "GitHub", url: "https://github.com", icon: "link" },
          { label: "LinkedIn", url: "https://linkedin.com", icon: "linkedin" },
          { label: "YouTube", url: "https://youtube.com", icon: "youtube" },
        ],
        scrollTopLabel: "Back to top",
        navColumnTitle: "Navigate",
        navLinks: [
          { label: "Hero", anchorId: "hero" },
          { label: "Features", anchorId: "features" },
          { label: "Timeline", anchorId: "timeline" },
          { label: "Pricing", anchorId: "pricing" },
          { label: "FAQ", anchorId: "faq" },
        ],
        linksColumnOneTitle: "Resources",
        linksColumnOne: [
          { label: "Docs", url: "#" },
          { label: "Changelog", url: "#" },
        ],
        linksColumnTwoTitle: "Contact",
        linksColumnTwo: [
          { label: "Support", url: "#" },
          { label: "Sales", url: "#" },
        ],
      },
    },
  ],
};
